Syntax error corrections to fvwmrc_convert (oops!)

diff --git a/utils/fvwmrc_convert b/utils/fvwmrc_convert
--- a/utils/fvwmrc_convert
+++ b/utils/fvwmrc_convert
@@ -17,8 +17,12 @@
 # case of the fvwm commands must match those in the script
 # exactly). With gawk, it'll be case-insensitive.
 
+# It's not perfect: some old commands slip through, especially in the
+# context of Mouse and Key commands.  But it provides a good basis on
+# which to go further.
+
 #
-# Convert fvwm 1.x configuration file to 2.0
+# Convert fvwm 1.x configuration file to 2.2 configuration file
 #
 # Originally written by Martin Kraemer <Martin.Kraemer@mch.sni.de>
 # Corrected, extended, and modified by Grant McDorman <grant@isgtec.com>
@@ -29,17 +33,38 @@
 # Further minor corrections by Julian Gilbey <jdg@debian.org> based on those
 # of Austin Donnelly <and1000@debian.org>, 1 Mar 1999
 # Further major corrections by Julian Gilbey <jdg@debian.org>, 3 Mar 1999
+# and minor corrections March - May 1999.
+# Correct some major gaffs: Julian Gilbey, January 2000, with thanks to
+# Victor Meghesan <victorm@genesys.ro>
 
 echo "fvwmrc-to-fvwm2rc" >&2
 
-# Point this to your gawk/nawk/awk exec:
-AWK=/usr/bin/awk
+# gawk has IGNORECASE, so we use it if possible.
+if [ -n `command -v gawk 2>/dev/null` ]
+then
+   AWK=`command -v gawk`
+elif [ -x /usr/bin/gawk ]
+then
+   AWK=/usr/bin/gawk
+elif [ -n `command -v awk 2>/dev/null` ]
+then
+   AWK=`command -v awk`
+elif [ -x /usr/bin/awk ]
+then
+   AWK=/usr/bin/awk
+fi
 
 if [ ! -x $AWK ];then
-   echo "$AWK missing, cannot run" >&2
+   echo "Can't find any awk, cannot run!" >&2
    exit 1
 fi
+
 source=${1:-$HOME/.fvwmrc}
+if [ ! -r $source ] ; then
+	echo "Can't find source file $source, giving up" >&2
+	exit 1
+fi
+
 dest=${2:-$HOME/.fvwm2rc}
 if [ "$dest" != "-" ] ;then
 	echo "Output to $dest" >&2
@@ -163,7 +188,7 @@ BEGIN   {
 /^[ \t]*ButtonStyle[ \t]*/	{
         if ($2 == ":") {  # new style already
            if (NF != $4+4)
-	       print "ERROR: ButtonStyle command incorrect\n" NR $0 >"'$TTY'";
+	       print "ERROR: ButtonStyle command incorrect\n" NR ": " $0 >"'$TTY'";
 	   printf ("%s %d %d", $1, $3, $4);
 	   for (i=5; i<=NF; ++i)
 	       printf (" %s", $i);
@@ -219,7 +244,10 @@ BEGIN   {
 ########## Placement & Focus styles ##########
 /^[ \t]*RandomPlacement[ \t]*/	{ print "Style \"*\" " $0; placement = TRUE; next; }
 /^[ \t]*SmartPlacement[ \t]*/	{ print "Style \"*\" " $0; placement = TRUE; next; }
-/^[ \t]*Sticky[ \t]*/		{ printf "Style \"%s\" Sticky\n", $2; next; }
+/^[ \t]*Sticky(Back|Fore)Color[ \t]*/ {
+      print "#! " $0 " (not supported in FVWM2)"; next;
+}
+/^[ \t]*Sticky[ \t]+/		{ printf "Style \"%s\" Sticky\n", $2; next; }
 /^[ \t]*NoPPosition[ \t]*/	{ print "Style \"*\" " $0; next; }
 /^[ \t]*ClickToFocus[ \t]*/	{ print "Style \"*\" " $0; next; }
 /^[ \t]*SloppyFocus[ \t]*/	{ print "Style \"*\" " $0; next; }
@@ -300,9 +328,9 @@ BEGIN   {
 # 		 print $0; next;
 # }
 
-/^[ \t]*WindowListSkip[ \t]*/	{ printf "Style %s WindowListSkip", $2; next; }
+/^[ \t]*WindowListSkip[ \t]*/	{ printf "Style %s WindowListSkip\n", $2; next; }
 /^[ \t]*WindowFont[ \t]*/	{ print $0; next; }
-/^[ \t]*ClickTime[ \t]*/		{ print $0; next; }
+/^[ \t]*ClickTime[ \t]*/	{ print $0; next; }
 /^[ \t]*OpaqueMove[ \t]*/	{ print "OpaqueMoveSize " $2; next; }
 /^[ \t]*EdgeScroll[ \t]*/	{ print $0; next; }
 /^[ \t]*EdgeResistance[ \t]*/	{ print $0; next; }
@@ -324,6 +352,7 @@ BEGIN   {
 	if (!warn["GoodStuff"])
 	{
 	    print "Note: GoodStuff renamed to FvwmButtons" >"'$TTY'";
+	    print "Note: FvwmButtons syntax may now be wrong; please check!" >"'$TTY'";
 	    warn["GoodStuff"]=TRUE;
 	}
 	next;
@@ -342,10 +371,10 @@ BEGIN   {
 # hack: function declarations cannot have leading whitespace
 /^Function[ \t]*/		{
 	if (inpopup)
-	   print "ERROR: EndPopup missing\n" NR $0 >"'$TTY'";
+	   print "ERROR: EndPopup missing\n" NR ": " $0 >"'$TTY'";
 	inpopup=FALSE;
 	if (infunction)
-	   print "ERROR: EndFunction missing\n" NR $0 >"'$TTY'";
+	   print "ERROR: EndFunction missing\n" NR ": " $0 >"'$TTY'";
 	infunction=TRUE;
 	prefix="AddToFunc " $2;
 	next;
@@ -362,9 +391,9 @@ BEGIN   {
 # hack: popup declarations cannot have leading whitespace
 /^Popup/                        {
         if (inpopup) 
-	   print "ERROR: EndPopup missing\n" NR $0 >"'$TTY'";
+	   print "ERROR: EndPopup missing\n" NR ": " $0 >"'$TTY'";
         if (infunction)
-	   print "ERROR: EndFunction missing\n" NR $0 >"'$TTY'";
+	   print "ERROR: EndFunction missing\n" NR ": " $0 >"'$TTY'";
         infunction=FALSE;
 	inpopup=TRUE;
 
@@ -387,7 +416,7 @@ BEGIN   {
 
 /^[ \t]*EndPopup[ \t]*/		{
         if (!inpopup)
-	   print "ERROR: EndPopup outside of popup\n" NR $0 >"'$TTY'";
+	   print "ERROR: EndPopup outside of popup\n" NR ": " $0 >"'$TTY'";
         inpopup=FALSE;
 	prefix="";
 	next;
